fooocus_mapping = {
    # EnhanceControls
    ("10", "inputs", "enhance_enabled", ): ("enhance_ctrls", 0, "enhance_enabled",),
    ("10", "inputs", "enhance_mask_dino_prompt", ): ("enhance_ctrls", 0, "enhance_mask_dino_prompt",),
    ("10", "inputs", "enhance_prompt", ): ("enhance_ctrls", 0, "enhance_prompt",),
    ("10", "inputs", "enhance_negative_prompt", ): ("enhance_ctrls", 0, "enhance_negative_prompt",),
    ("10", "inputs", "enhance_mask_model", ): ("enhance_ctrls", 0, "enhance_mask_model",),
    ("10", "inputs", "enhance_mask_cloth_category", ): ("enhance_ctrls", 0, "enhance_mask_cloth_category",),
    ("10", "inputs", "enhance_mask_sam_model", ): ("enhance_ctrls", 0, "enhance_mask_sam_model",),
    ("10", "inputs", "enhance_mask_text_threshold", ): ("enhance_ctrls", 0, "enhance_mask_text_threshold",),
    ("10", "inputs", "enhance_mask_box_threshold", ): ("enhance_ctrls", 0, "enhance_mask_box_threshold",),
    ("10", "inputs", "enhance_mask_sam_max_detections", ): ("enhance_ctrls", 0, "enhance_mask_sam_max_detections",),
    ("10", "inputs", "enhance_inpaint_disable_initial_latent", ): ("enhance_ctrls", 0, "enhance_inpaint_disable_initial_latent",),
    ("10", "inputs", "enhance_inpaint_engine", ): ("enhance_ctrls", 0, "enhance_inpaint_engine",),
    ("10", "inputs", "enhance_inpaint_strength", ): ("enhance_ctrls", 0, "enhance_inpaint_strength",),
    ("10", "inputs", "enhance_inpaint_respective_field", ): ("enhance_ctrls", 0, "enhance_inpaint_respective_field",),
    ("10", "inputs", "enhance_inpaint_erode_or_dilate", ): ("enhance_ctrls", 0, "enhance_inpaint_erode_or_dilate",),
    ("10", "inputs", "enhance_mask_invert", ): ("enhance_ctrls", 0, "enhance_mask_invert",),

    ("13", "inputs", "enhance_enabled", ): ("enhance_ctrls", 1, "enhance_enabled",),
    ("13", "inputs", "enhance_mask_dino_prompt", ): ("enhance_ctrls", 1, "enhance_mask_dino_prompt",),
    ("13", "inputs", "enhance_prompt", ): ("enhance_ctrls", 1, "enhance_prompt",),
    ("13", "inputs", "enhance_negative_prompt", ): ("enhance_ctrls", 0, "enhance_negative_prompt",),
    ("13", "inputs", "enhance_mask_model", ): ("enhance_ctrls", 1, "enhance_mask_model",),
    ("13", "inputs", "enhance_mask_cloth_category", ): ("enhance_ctrls", 1, "enhance_mask_cloth_category",),
    ("13", "inputs", "enhance_mask_sam_model", ): ("enhance_ctrls", 1, "enhance_mask_sam_model",),
    ("13", "inputs", "enhance_mask_text_threshold", ): ("enhance_ctrls", 1, "enhance_mask_text_threshold",),
    ("13", "inputs", "enhance_mask_box_threshold", ): ("enhance_ctrls", 1, "enhance_mask_box_threshold",),
    ("13", "inputs", "enhance_mask_sam_max_detections", ): ("enhance_ctrls", 1, "enhance_mask_sam_max_detections",),
    ("13", "inputs", "enhance_inpaint_disable_initial_latent", ): ("enhance_ctrls", 1, "enhance_inpaint_disable_initial_latent",),
    ("13", "inputs", "enhance_inpaint_engine", ): ("enhance_ctrls", 1, "enhance_inpaint_engine",),
    ("13", "inputs", "enhance_inpaint_strength", ): ("enhance_ctrls", 1, "enhance_inpaint_strength",),
    ("13", "inputs", "enhance_inpaint_respective_field", ): ("enhance_ctrls", 1, "enhance_inpaint_respective_field",),
    ("13", "inputs", "enhance_inpaint_erode_or_dilate", ): ("enhance_ctrls", 1, "enhance_inpaint_erode_or_dilate",),
    ("13", "inputs", "enhance_mask_invert", ): ("enhance_ctrls", 1, "enhance_mask_invert",),

    ("14", "inputs", "enhance_enabled", ): ("enhance_ctrls", 2, "enhance_enabled",),
    ("14", "inputs", "enhance_mask_dino_prompt", ): ("enhance_ctrls", 2, "enhance_mask_dino_prompt",),
    ("14", "inputs", "enhance_prompt", ): ("enhance_ctrls", 2, "enhance_prompt",),
    ("14", "inputs", "enhance_negative_prompt", ): ("enhance_ctrls", 2, "enhance_negative_prompt",),
    ("14", "inputs", "enhance_mask_model", ): ("enhance_ctrls", 2, "enhance_mask_model",),
    ("14", "inputs", "enhance_mask_cloth_category", ): ("enhance_ctrls", 2, "enhance_mask_cloth_category",),
    ("14", "inputs", "enhance_mask_sam_model", ): ("enhance_ctrls", 2, "enhance_mask_sam_model",),
    ("14", "inputs", "enhance_mask_text_threshold", ): ("enhance_ctrls", 2, "enhance_mask_text_threshold",),
    ("14", "inputs", "enhance_mask_box_threshold", ): ("enhance_ctrls", 2, "enhance_mask_box_threshold",),
    ("14", "inputs", "enhance_mask_sam_max_detections", ): ("enhance_ctrls", 2, "enhance_mask_sam_max_detections",),
    ("14", "inputs", "enhance_inpaint_disable_initial_latent", ): ("enhance_ctrls", 2, "enhance_inpaint_disable_initial_latent",),
    ("14", "inputs", "enhance_inpaint_engine", ): ("enhance_ctrls", 2, "enhance_inpaint_engine",),
    ("14", "inputs", "enhance_inpaint_strength", ): ("enhance_ctrls", 2, "enhance_inpaint_strength",),
    ("14", "inputs", "enhance_inpaint_respective_field", ): ("enhance_ctrls", 2, "enhance_inpaint_respective_field",),
    ("14", "inputs", "enhance_inpaint_erode_or_dilate", ): ("enhance_ctrls", 2, "enhance_inpaint_erode_or_dilate",),
    ("14", "inputs", "enhance_mask_invert", ): ("enhance_ctrls", 2, "enhance_mask_invert",),

    # LoraStacks
    ("15", "inputs", "lora_1_enable", ): ("loras", 0, "enabled",),
    ("15", "inputs", "lora_1_name", ): ("loras", 0, "model_name",),
    ("15", "inputs", "lora_1_strength", ): ("loras", 0, "weight",),
    ("15", "inputs", "lora_2_enable", ): ("loras", 1, "enabled",),
    ("15", "inputs", "lora_2_name", ): ("loras", 1, "model_name",),
    ("15", "inputs", "lora_2_strength", ): ("loras", 1, "weight",),
    ("15", "inputs", "lora_3_enable", ): ("loras", 2, "enabled",),
    ("15", "inputs", "lora_3_name", ): ("loras", 2, "model_name",),
    ("15", "inputs", "lora_3_strength", ): ("loras", 2, "weight",),
    ("15", "inputs", "lora_4_enable", ): ("loras", 3, "enabled",),
    ("15", "inputs", "lora_4_name", ): ("loras", 3, "model_name",),
    ("15", "inputs", "lora_4_strength", ): ("loras", 3, "weight",),
    ("15", "inputs", "lora_5_enable", ): ("loras", 4, "enabled",),
    ("15", "inputs", "lora_5_name", ): ("loras", 4, "model_name",),
    ("15", "inputs", "lora_5_strength", ): ("loras", 5, "weight",),
    # ImagePrompts
    ("20", "inputs", "cn_img_1", ): ("controlnet_image", 0, "cn_img"),
    ("20", "inputs", "cn_stop_1", ): ("controlnet_image", 0, "cn_stop"),
    ("20", "inputs", "cn_weight_1", ): ("controlnet_image", 0, "cn_weight"),
    ("20", "inputs", "cn_type_1", ): ("controlnet_image", 0, "cn_type"),
    ("20", "inputs", "cn_img_2", ): ("controlnet_image", 1, "cn_img"),
    ("20", "inputs", "cn_stop_2", ): ("controlnet_image", 1, "cn_stop"),
    ("20", "inputs", "cn_weight_2", ): ("controlnet_image", 1, "cn_weight"),
    ("20", "inputs", "cn_type_2", ): ("controlnet_image", 1, "cn_type"),
    ("20", "inputs", "cn_img_3", ): ("controlnet_image", 2, "cn_img"),
    ("20", "inputs", "cn_stop_3", ): ("controlnet_image", 2, "cn_stop"),
    ("20", "inputs", "cn_weight_3", ): ("controlnet_image", 2, "cn_weight"),
    ("20", "inputs", "cn_type_3", ): ("controlnet_image", 2, "cn_type"),
    ("20", "inputs", "cn_img_4", ): ("controlnet_image", 3, "cn_img"),
    ("20", "inputs", "cn_stop_4", ): ("controlnet_image", 3, "cn_stop"),
    ("20", "inputs", "cn_weight_4", ): ("controlnet_image", 3, "cn_weight"),
    ("20", "inputs", "cn_type_4", ): ("controlnet_image", 3, "cn_type"),
    # ImageEnhances
    ("21", "inputs", "enhance_image", ): ("enhance_input_image",),
    ("21", "inputs", "enhance_enable", ): ("enhance_checkbox",),
    ("21", "inputs", "enhance_uov_method", ): ("enhance_uov_method",),
    ("21", "inputs", "enhance_uov_processing_order", ): ("enhance_uov_processing_order",),
    ("21", "inputs", "enhance_uov_prompt_type", ): ("enhance_uov_prompt_type",),
    # InpaintOutpaint
    ("25", "inputs", "input_image"): ("inpaint_input_image",),
    ("25", "inputs", "input_mask", ): ("inpaint_mask_image_upload",),
    ("25", "inputs", "inpaint_prompt", ): ("inpaint_additional_prompt",),
    ("25", "inputs", "inpaint_disable_initial_latent", ): ("inpaint_disable_initial_latent",),
    ("25", "inputs", "inpaint_engine", ): ("inpaint_engine",),
    ("25", "inputs", "inpaint_strength", ): ("inpaint_strength",),
    ("25", "inputs", "inpaint_respective_field", ): ("inpaint_respective_field",),
    ("25", "inputs", "inpaint_erode_or_dilate", ): ("inpaint_erode_or_dilate",),

    ("25", "inputs", "outpaint_left", ): ("outpaint_selections",),
    ("25", "inputs", "outpaint_left_distance", ): ("outpaint_distance",),
    ("25", "inputs", "outpaint_right", ): ("outpaint_selections",),
    ("25", "inputs", "outpaint_right_distance", ): ("outpaint_distance",),
    ("25", "inputs", "outpaint_top", ): ("outpaint_selections",),
    ("25", "inputs", "outpaint_top_distance", ): ("outpaint_distance",),
    ("25", "inputs", "outpaint_bottom", ): ("outpaint_selections",),
    ("25", "inputs", "outpaint_bottom_distance", ): ("outpaint_distance",),
    # UpscaleVary
    ("26", "inputs", "uov_input_image"): ("uov_input_image",),
    ("26", "inputs", "uov_method"): ("uov_method",),
    ("26", "inputs", "upscale_multiple"): ("upscale_multiple",),
    # Settings
    ("31", "inputs", "adaptive_cfg", ): ("adaptive_cfg",),
    ("31", "inputs", "adm_scaler_positive", ): ("adm_scaler_positive",),
    ("31", "inputs", "adm_scaler_negative", ): ("adm_scaler_negative",),
    ("31", "inputs", "adm_scaler_end", ): ("adm_scaler_end",),
    ("31", "inputs", "black_out_nsfw", ): ("black_out_nsfw",),
    ("31", "inputs", "canny_low_threshold", ): ("canny_low_threshold",),
    ("31", "inputs", "canny_high_threshold", ): ("canny_high_threshold",),
    ("31", "inputs", "controlnet_softness", ): ("controlnet_softness",),
    ("31", "inputs", "clip_skip", ): ("clip_skip",),
    ("31", "inputs", "debugging_cn_preprocessor", ): ("debugging_cn_preprocessor",),
    ("31", "inputs", "debugging_dino", ): ("debugging_dino",),
    ("31", "inputs", "dino_erode_or_dilate", ): ("dino_erode_or_dilate",),
    ("31", "inputs", "debugging_enhance_masks_checkbox", ): ("debugging_enhance_masks_checkbox",),
    ("31", "inputs", "debugging_inpaint_preprocessor", ): ("debugging_inpaint_preprocessor",),
    ("31", "inputs", "disable_preview", ): ("disable_preview",),
    ("31", "inputs", "disable_intermediate_results", ): ("disable_intermediate_results",),
    ("31", "inputs", "disable_seed_increment", ): ("disable_seed_increment",),
    ("31", "inputs", "freeu_enabled", ): ("freeu_enabled",),
    ("31", "inputs", "freeu_b1", ): ("freeu_b1",),
    ("31", "inputs", "freeu_b2", ): ("freeu_b2",),
    ("31", "inputs", "freeu_s1", ): ("freeu_s1",),
    ("31", "inputs", "freeu_s2", ): ("freeu_s2",),
    ("31", "inputs", "generate_image_grid", ): ("generate_image_grid",),
    ("31", "inputs", "mixing_image_prompt_and_vary_upscale", ): ("mixing_image_prompt_and_vary_upscale",),
    ("31", "inputs", "mixing_image_prompt_and_inpaint", ): ("mixing_image_prompt_and_inpaint",),
    ("31", "inputs", "output_format", ): ("output_format",),
    ("31", "inputs", "overwrite_step", ): ("overwrite_step",),
    ("31", "inputs", "overwrite_switch", ): ("overwrite_switch",),
    ("31", "inputs", "overwrite_width", ): ("overwrite_width",),
    ("31", "inputs", "overwrite_height", ): ("overwrite_height",),
    ("31", "inputs", "overwrite_vary_strength", ): ("overwrite_vary_strength",),
    ("31", "inputs", "overwrite_upscale_strength", ): ("overwrite_upscale_strength",),
    ("31", "inputs", "read_wildcards_in_order", ): ("read_wildcards_in_order",),
    ("31", "inputs", "skipping_cn_preprocessor", ): ("skipping_cn_preprocessor",),
    # FooocusSampler
    ("36", "inputs", "style_selections",): ("style_selections",),
    ("36", "inputs", "aspect_ratios_selection",): ("aspect_ratios_selection",),
    ("36", "inputs", "performance_selection",): ("performance_selection",),
    ("36", "inputs", "image_number",): ("image_number",),
    ("36", "inputs", "sharpness",): ("sharpness",),
    ("36", "inputs", "guidance_scale",): ("guidance_scale",),
    ("36", "inputs", "base_model_name",): ("base_model_name",),
    ("36", "inputs", "refiner_model_name",): ("refiner_model_name",),
    ("36", "inputs", "refiner_switch",): ("refiner_switch",),
    ("36", "inputs", "refiner_swap_method",): ("refiner_swap_method",),
    ("36", "inputs", "preset",): ("preset",),
    ("36", "inputs", "sampler_name",): ("sampler_name",),
    ("36", "inputs", "scheduler_name",): ("scheduler_name",),
    ("36", "inputs", "vae_name",): ("vae_name",),
    # Easy seed
    ("42", "inputs", "seed",): ("image_seed",),
    # Prompt
    ("50", "inputs", "positive",): ("prompt",),
    # Negative
    ("51", "inputs", "negative",): ("negative_prompt",)
}
